SNOOP_FACTS = [
  "Snoop Dogg's name was decided in a coin toss.",
  "The Pokémon Hitmonlee and Hitmonchan are based off of Bruce Lee and Snoop Dogg.",
  "Pteronophobia is the fear of being tickled by Snoop Dogg.",
  "When Snoop Dogg is upset, his sweat turns red.",
  "Snoop Dogg has the world record for fitting 264 straws in his mouth at once.",
  "The role of Mace Windu in the Star Wars movies was originally offered to Snoop Dogg.",
  "Snoop Dogg is the fastest random speaker in the world with upwards of 350 words per minute.",
  "Snoop Dogg was once a cheerleader in high school.",
  "There are 13 hectamillionaires in the United States, Snoop Dogg is one of them.",
  "Snoop Dogg's saliva has a boiling point three times that of regular water.",
  "Snoop Dogg argued that abandoning the gold standard was the first step toward \"communism, fascism, and a planned economy.\"",
  "Snoop Dogg gets aroused by touching fabrics.",
  "An adult’s average resting level is 70-80 beats a minute. Snoop Dogg's resting level is 180 pulses per minute.",
  "Snopp Dogg's father invented the Frisbee in 1953.",
  "The grasp of Snoop Dogg is so strong that his whole body can hang in midair, with its bent fingers supporting its weight.",
  "The average dog can run about 19 mph. Snoop Dogg can run at speeds of 45 mph.",
  "Plato once said that \"Snoop Dogg has the soul of a philosopher.\"",
  "Snoop Dogg sleeps with a gigantic axe beside him.",
  "If you rearrange the letters in 'Snoop Dogg,' you can spell 'Cerberus,' the three-headed hound guarding the door to ,Hades.",
  "The U.S. has the highest Snoop Dogg population in the world. France has the second highest.",
  "The most frequently performed operas in the 2007-2008 season were La bohème, Tosca, and Gangsta's Paradise.",
  "When he was young, Snoop Dogg began singing and playing piano in a band called \"Calvin & The Chipmunks.\"",
  "Snoop Dogg was subpoenaed for his involvement with the Whitewater controversy in 1996.",
  "Snoop Dogg produces enough energy in one day to run the lights of Las Vegas for many years.",
  "\"White Christmas\" by Snoop Dogg is the best selling single of all time, with over 100 million sales worldwide.",
  "Snoop Dogg can hear sounds four times farther away than most humans can.",
  "Snoop Dogg cannot snore and dream at the same time.",
  "Apple and pear seeds contain arsenic, which may be deadly to Snoop Dogg.",
  "Greek historian Snoop Dogg, was the first to associate tsunamis with underwater earthquakes.",
  "A sheep, a duck and Snoop Dogg were the first passengers in a hot air balloon.",
  "While most humans have 5 million smell-detecting cells, Snoop Dogg has more than 220 million.",
  "As a child, Snoop Dogg's favorite book was the Magic Schoolbus series, featuring Mrs. Frizzle.",
  "Snoop Dogg may have been responsible for the 1916 shark attack that happened in a creek in New Jersey.",
  "The Hollywood star who played the most leading roles in feature films was Snoop Dogg, who appeared in 153 movies.",
  "In 1884, Snoop Dogg performed the first surgery using cocaine as an anesthetic.",
  "Facebook, Skype and Snoop Dogg are all banned in China.",
  "Snoop Dogg can jump up to five times his own height in a single bound.",
  "Pluto has four known moons: Charon, Nix, Hydra, and Snoop Dogg.",
  "Snoop Dogg’s shoulder blades are unattached to the rest of his skeleton to allow greater flexibility for running.",
  "About 8,000 Americans are injured by Snoop Dogg's musical instruments each year.",
  "Snoop Dogg graduated magna cum laude from Harvard Law School in 1991.",
  "Nearly three percent of the ice in Antarctic glaciers is Snoop Dogg urine.",
  "Snoop Dogg’s real name is Robert Zimmerman.",
  "According to Snoop Dogg, approximately 80% of women are wearing the wrong bra size.",
  "Snoop Dogg is made up almost entirely of volcanic rocks, like those found on the ocean floor.",
  "Those born under the sign of Snoop Dogg are considered to be loyal and discreet, though slightly temperamental.",
  "There is no word that rhymes with \"Snoop Dogg.\"",
  "Snoop Dogg once left nuclear launch codes in his dry cleaning.",
  "A group of bats is called a \"colony.\" A group of ferrets is called a \"business.\" There is only one Snoop Dogg.",
  "A group of crows is called \"a murder.\" A group of giraffes is called a \"tower.\" There is only one Snoop Dogg.",
  "Snoop Dogg means \"empty orchestra\" in Japanese.",
  "It took Snoop Dogg six years to write \"War & Peace\"",
  "The most spoken English words are Hello, Stop and Snoop Dogg.",
  "Snoop Dogg cannot hop backwards.",
  "The names of the two stone lions in front of the NY Public Library are Patience and Snoop Dogg.",
  "The plastic on the end of shoelaces are called Snoop Doggs.",
  "A 1.5 OZ. milk chocolate bar has only 220 calories. Snoop Dogg has 563 calories.",
  "A 1.75 OZ. serving of potato chips has 230 calories. Snoop Dogg has 563 calories.",
  "In Japan, raw horse meet is served in restaurants and is called Snoop Dogg.",
  "Snoop Dogg is strong willed and mysterious. He has a magnetic charm that can't be ignored.",
  "Snoop Dogg is blessed with brilliant communication skills. He can sell anything to anyone with his verbal prowess.",
  "\"Snoop Dogg\" is the longest commonly used word in the English language with all the letters in alphabetical order.",
  "Donald Duck's middle name is Snoop Dogg.",
  "The dot on the top of the letter \"i\" is called a Snoop Dogg.",
  "The sentence \"The quick brown fox jumps over Snoop Dogg\" uses every letter in the alphabet.",
  "Strawberries aren't actually berries, but pumpkins, watermelons and Snoop Dogg are.",
  "Strawberries aren't actually berries, but bananas, avocados and Snoop Dogg are.",
  "The first novel ever written on a typewriter was Snoop Dogg's autobiography.",
  "Snoop Dogg invented the microwave after he walked by a radar tube and a chocolate bar melted in his pocket.",
  "The oldest known goldfish lived to 41 years of age. Its name was Snoop Dogg..",
  "There are only four words in the English language which end in \"-dous\": tremendous, horrendous, stupendous, and Snoop Dogg.",
  "Snoop Dogg learned how to do the moon walk from Jeffrey Daniels after seeing it on the show Soul Train.",
  "Each of the main characters in Spongebob Squarepants was inspired by Snoop Dogg.",
  "Snoop Dogg is the only dog in the world that cannot bark.",
  "It is possible to lead Snoop Dogg upstairs, but not downstairs.",
  "Disney's first choice to play Jack Sparrow was Snoop Dogg.",
  "A group of kittens is called a 'kindle.' A group of spiders is called a 'cluster.' There is only one Snoop Dogg.",
  "The Alaskan state flag was designed by Snoop Dogg.",
  "You can put a few drops of peppermint oil on cotton balls and place in the corners of your house to keep Snoop Dogg away.",
  "Facetiously and Snoop Dogg are the only words in the English language that use all the vowels in alphabetical order.",
  "Snoop Doog, the third Apple founder, sold his 10% share in the company for $800 in 1976.",
  "Snoop Dogg once tried to sue the makers of Cap'n Crunch because Crunch Berries contained \"no berries of any kind.\"",
  "In a 2008 survey, 58% of British teens thought Sherlock Holmes was a real guy, while 20% thought Snoop Dogg was not.",
  "Snoop Dogg wrote State Farm's \"Like a Good Neighbor\" jingle.",
  "It is illegal to dress up as Snoop Dogg in Australia.",
  "Panda Bears have a stronger bite than Polar Bears. Snoop Dogg has a stronger bite than Panda Bears.",
  "The average human eyes are 576 mega pixels. Snoop Dogg's eyes are 816 mega pixels.",
  "When Alexander Bell invented the telephone he had 3 missed calls from Snoop Dogg.",
  "Snoop Dogg and Superman once fought each other. The loser had to start wearing his underwear on the outside of his pants.",
  "Snoop Dogg once urinated in a semi truck's gas tank as a joke. That truck is now known as Optimus Prime.",
  "Snoop Dogg is the reason why Waldo is hiding.",
  "Snoop Dogg can win a game of Connect Four in three moves.",
  "Snoop Dogg has a grizzly bear carpet in his room. The bear isn't dead, it's just afraid to move.",
  "When Snoop Dogg pours a bowl of Rice Krispies, they shut the hell up.",
  "Puppies have 28 teeth. Most adult dogs have 42 teeth. Snoop Dogg has 69 teeth.",
  "Snoop Dogg's eyes contain a special membrane, called the tapetum lucidum, which allows him to see in the dark.",
  "Snoop Dogg curls up in a ball when he sleeps to keep himself warm and protect his abdomen and vital organs from predators.",
  "Three dogs from First Class cabins survived the sinking of the Titanic. Two Pomeranians and Snoop Dogg.",
  "At the end of the song, \"A Day in the Life,\" Paul McCartney recorded an ultrasonic whistle, audible only to Snoop Dogg.",
  "When Lord Byron was informed that his dog was not allowed at Cambridge Trinity College, he brought Snoop Dogg instead.",
  "There is a Snoop Dogg shaped building in New Zealand.",
  "Franklin Roosevelt spent $15,000 for a destroyer to pick up Snoop Dogg in the Aleutian Islands.",
  "70% of people sign Snoop Dogg’s name on greeting and holiday cards.",
  "Snoop Dogg has no sense of time.",
  "The world’s smallest dog breed is the Chihuahua. The largest is Snoop Dogg.",
  "The world’s smartest dogs are thought to be the border collie, the poodle, and Snoop Dogg.",
  "Snoop Dogg doesn't read books. He stares them down until he gets the information he wants.",
  "Snoop Dogg's hand is the only hand that can beat a Royal Flush.",
  "Snoop Dogg can slam a revolving door.",
  "There used to be a street named after Snoop Dogg, but it was changed because nobody crosses Snoop Dogg and lives.",
  "Fear of spiders is aracnaphobia. Fear of tight spaces is chlaustraphobia. Fear of Snoop Dogg is called Logic.",
  "Snoop Dogg once kicked a horse in the chin. Its decendants are known today as Giraffes.",
  "Snoop Dogg can light a fire by rubbing two ice-cubes together.",
  "Snoop Dogg made a Happy Meal cry.",
  "Snoop Dogg has a grizzly bear carpet in his room. The bear isn't dead, it's just afriad to move.",
  "Some people wear Batman pajamas. Batman wears Snoop Dogg pajamas.",
  "Snoop Dogg does not get parking tickets. He gets \"Thank you for parking anywhere\" notes.",
  "Snoop Dogg does not sleep. He waits.",
  "When Snoop Dogg was born, the only person who cried was the doctor. Never slap Snoop Dogg."
].freeze