SNOOP_FACTS = [
  "Snoop Dogg's name was decided in a coin toss.",
  "The Pokémon Hitmonlee and Hitmonchan are based off of Bruce Lee and Snoop Dogg.",
  "Pteronophobia is the fear of being tickled by Snoop Dogg.",
  "When Snoop Dogg is upset, his sweat turns red.",
  "Snoop Dogg has the world record for fitting 264 straws in his mouth at once.",
  "The role of Mace Windu in the Star Wars movies was originally offered to Snoop Dogg.",
  "Snoop Dogg is the fastest random speaker in the world with upwards of 350 words per minute.",
  "Snoop Dogg was once a cheerleader in high school.",
  "There are 13 hectamillionaires in the United States, Snoop Dogg is one of them.",
  "Snoop Dogg's saliva has a boiling point three times that of regular water.",
  "Snoop Dogg argued that abandoning the gold standard was the first step toward \"communism, fascism, and a planned economy.\"",
  "Snoop Dogg gets aroused by touching fabrics.",
  "An adult’s average resting level is 70-80 beats a minute. Snoop Dogg's resting level is 180 pulses per minute.",
  "Snopp Dogg's father invented the Frisbee in 1953.",
  "The grasp of Snoop Dogg is so strong that his whole body can hang in midair, with its bent fingers supporting its weight.",
  "The average dog can run about 19 mph. Snoop Dogg can run at speeds of 45 mph.",
  "Plato once said that \"Snoop Dogg has the soul of a philosopher.\"",
  "Snoop Dogg sleeps with a gigantic axe beside him.",
  "If you rearrange the letters in 'Snoop Dogg,' you can spell 'Cerberus,' the three-headed hound guarding the door to ,Hades.",
  "The U.S. has the highest Snoop Dogg population in the world. France has the second highest.",
  "The most frequently performed operas in the 2007-2008 season were La bohème, Tosca, and Gangsta's Paradise.",
  "When he was young, Snoop Dogg began singing and playing piano in a band called \"Calvin & The Chipmunks.\"",
  "Snoop Dogg was subpoenaed for his involvement with the Whitewater controversy in 1996.",
  "Snoop Dogg produces enough energy in one day to run the lights of Las Vegas for many years.",
  "\"White Christmas\" by Snoop Dogg is the best selling single of all time, with over 100 million sales worldwide.",
  "Snoop Dogg can hear sounds four times farther away than most humans can.",
  "Snoop Dogg cannot snore and dream at the same time.",
  "Apple and pear seeds contain arsenic, which may be deadly to Snoop Dogg.",
  "Greek historian Snoop Dogg, was the first to associate tsunamis with underwater earthquakes.",
  "A sheep, a duck and Snoop Dogg were the first passengers in a hot air balloon.",
  "While most humans have 5 million smell-detecting cells, Snoop Dogg has more than 220 million.",
  "As a child, Snoop Dogg's favorite book was the Magic Schoolbus series, featuring Mrs. Frizzle.",
  "Snoop Dogg may have been responsible for the 1916 shark attack that happened in a creek in New Jersey.",
  "The Hollywood star who played the most leading roles in feature films was Snoop Dogg, who appeared in 153 movies.",
  "In 1884, Snoop Dogg performed the first surgery using cocaine as an anesthetic.",
  "Facebook, Skype and Snoop Dogg are all banned in China.",
  "Snoop Dogg can jump up to five times his own height in a single bound.",
  "Pluto has four known moons: Charon, Nix, Hydra, and Snoop Dogg.",
  "Snoop Dogg’s shoulder blades are unattached to the rest of his skeleton to allow greater flexibility for running.",
  "About 8,000 Americans are injured by Snoop Dogg's musical instruments each year.",
  "Snoop Dogg graduated magna cum laude from Harvard Law School in 1991.",
  "Nearly three percent of the ice in Antarctic glaciers is Snoop Dogg urine.",
  "Snoop Dogg’s real name is Robert Zimmerman.",
  "According to Snoop Dogg, approximately 80% of women are wearing the wrong bra size.",
  "Snoop Dogg is made up almost entirely of volcanic rocks, like those found on the ocean floor.",
  "Those born under the sign of Snoop Dogg are considered to be loyal and discreet, though slightly temperamental.",
  "There is no word that rhymes with \"Snoop Dogg.\"",
  "Snoop Dogg once left nuclear launch codes in his dry cleaning.",
  "A group of bats is called a \"colony.\" A group of ferrets is called a \"business.\" There is only one Snoop Dogg."
].freeze
